const randomRecipes = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 60,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 11,
    spoonacularScore: 82.0,
    healthScore: 35.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 1035.09,
    extendedIngredients: [
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "solid",
        name: "butter",
        nameClean: "butter",
        original: "1 tablespoon Butter or marg., melted",
        originalName: "Butter or marg., melted",
        amount: 1.0,
        unit: "tablespoon",
        meta: ["melted"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 18079,
        aisle: "Pasta and Rice",
        image: "breadcrumbs.jpg",
        consistency: "solid",
        name: "dry bread crumbs",
        nameClean: "breadcrumbs",
        original: "1 cup Dry bread crumbs",
        originalName: "Dry bread crumbs",
        amount: 1.0,
        unit: "cup",
        meta: ["dry"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1123,
        aisle: "Milk, Eggs, Other Dairy",
        image: "egg.png",
        consistency: "solid",
        name: "eggs",
        nameClean: "egg",
        original: "2 eggs",
        originalName: "eggs",
        amount: 2.0,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "solid",
        name: "flour",
        nameClean: "wheat flour",
        original: "3 tablespoons All-purpose flour",
        originalName: "All-purpose flour",
        amount: 3.0,
        unit: "tablespoons",
        meta: ["all-purpose"],
        measures: {
          us: {
            amount: 3.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 3.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 1022020,
        aisle: "Spices and Seasonings",
        image: "garlic-powder.png",
        consistency: "solid",
        name: "garlic powder",
        nameClean: "garlic powder",
        original: "1/2 teaspoon Garlic powder",
        originalName: "Garlic powder",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 1022027,
        aisle: "Spices and Seasonings",
        image: "dried-herbs.png",
        consistency: "solid",
        name: "italian seasoning",
        nameClean: "italian seasoning",
        original: "2 1/2 teaspoons Italian seasoning",
        originalName: "Italian seasoning",
        amount: 2.5,
        unit: "teaspoons",
        meta: ["italian"],
        measures: {
          us: {
            amount: 2.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 2.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 1002030,
        aisle: "Spices and Seasonings",
        image: "pepper.jpg",
        consistency: "solid",
        name: "pepper",
        nameClean: "black pepper",
        original: "1/8 teaspoon Pepper",
        originalName: "Pepper",
        amount: 0.125,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 0.125,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.125,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 10011549,
        aisle: "Pasta and Rice",
        image: "tomato-sauce-or-pasta-sauce.jpg",
        consistency: "solid",
        name: "spaghetti sauce",
        nameClean: "pasta sauce",
        original: "1 cup Marinara or spaghetti sauce, heated",
        originalName: "Marinara or spaghetti sauce, heated",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 98970,
        aisle: "Cheese",
        image: "string-cheese.png",
        consistency: "solid",
        name: "string cheese",
        nameClean: "string cheese",
        original: "12 string cheese",
        originalName: "string cheese",
        amount: 12.0,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 12.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 12.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "liquid",
        name: "water",
        nameClean: "water",
        original: "1 tablespoon Water",
        originalName: "Water",
        amount: 1.0,
        unit: "tablespoon",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
    ],
    id: 652513,
    title: "Mozzarella Sticks",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl: "http://www.foodista.com/recipe/LVT5MJLZ/mozzarella-sticks",
    image: "https://spoonacular.com/recipeImages/652513-556x370.jpg",
    imageType: "jpg",
    summary:
      'Mozzarella Sticks might be just the hor d\'oeuvre you are searching for. For <b>$10.35 per serving</b>, this recipe <b>covers 45%</b> of your daily requirements of vitamins and minerals. One serving contains <b>1773 calories</b>, <b>104g of protein</b>, and <b>98g of fat</b>. Head to the store and pick up flour, water, eggs, and a few other things to make it today. A couple people made this recipe, and 11 would say it hit the spot. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 83%</b>. This score is great. Try <a href="https://spoonacular.com/recipes/mozzarella-sticks-296374">Mozzarella Sticks</a>, <a href="https://spoonacular.com/recipes/mozzarella-sticks-675804">Mozzarella Sticks</a>, and <a href="https://spoonacular.com/recipes/mozzarella-sticks-79012">Mozzarella Sticks</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: [],
    occasions: [],
    instructions:
      "<ol><li>Taste of Home. It won a prize in their cheese contest. Mary Merchant of</li><li>In a small bowl, beat eggs and water. In a plastic bag, combine bread crumbs, Italian seasoning, garlic powder and pepper. Coat cheese sticks in flour, then dip in egg mixture and bread crumb mixture. Repeat egg and bread crumb coatings. Cover and chill for at least 4 hours or overnight.</li><li>Place on an ungreased baking sheet; drizzle with butter. Bake, uncovered, at 400 for 6 to 8 minutes or until heated through. Allow to stand for 3 to 5 minutes before serving. Use marinara or spaghetti sauce for dipping.</li><li>Yield: 4 to 6 servings.</li><li>Note: Regular mozzarella cheese, cut into 4 inch by 1/2 inch sticks can be substituted for the string cheese.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Taste of Home. It won a prize in their cheese contest. Mary Merchant ofIn a small bowl, beat eggs and water. In a plastic bag, combine bread crumbs, Italian seasoning, garlic powder and pepper. Coat cheese sticks in flour, then dip in egg mixture and bread crumb mixture. Repeat egg and bread crumb coatings. Cover and chill for at least 4 hours or overnight.",
            ingredients: [
              {
                id: 1022027,
                name: "italian seasoning",
                localizedName: "italian seasoning",
                image: "dried-herbs.png",
              },
              {
                id: 98970,
                name: "string cheese",
                localizedName: "string cheese",
                image: "string-cheese.png",
              },
              {
                id: 1022020,
                name: "garlic powder",
                localizedName: "garlic powder",
                image: "garlic-powder.png",
              },
              {
                id: 18079,
                name: "breadcrumbs",
                localizedName: "breadcrumbs",
                image: "breadcrumbs.jpg",
              },
              {
                id: 1041009,
                name: "cheese",
                localizedName: "cheese",
                image: "cheddar-cheese.png",
              },
              {
                id: 1002030,
                name: "pepper",
                localizedName: "pepper",
                image: "pepper.jpg",
              },
              {
                id: 18064,
                name: "bread",
                localizedName: "bread",
                image: "white-bread.jpg",
              },
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 1123,
                name: "egg",
                localizedName: "egg",
                image: "egg.png",
              },
              {
                id: 0,
                name: "dip",
                localizedName: "dip",
                image: "",
              },
            ],
            equipment: [
              {
                id: 221671,
                name: "ziploc bags",
                localizedName: "ziploc bags",
                image: "plastic-bag.jpg",
              },
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
            length: {
              number: 240,
              unit: "minutes",
            },
          },
          {
            number: 2,
            step: "Place on an ungreased baking sheet; drizzle with butter.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
            ],
            equipment: [
              {
                id: 404727,
                name: "baking sheet",
                localizedName: "baking sheet",
                image: "baking-sheet.jpg",
              },
            ],
          },
          {
            number: 3,
            step: "Bake, uncovered, at 400 for 6 to 8 minutes or until heated through. Allow to stand for 3 to 5 minutes before serving. Use marinara or spaghetti sauce for dipping.",
            ingredients: [
              {
                id: 10011549,
                name: "pasta sauce",
                localizedName: "pasta sauce",
                image: "tomato-sauce-or-pasta-sauce.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 9,
              unit: "minutes",
            },
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: "https://spoonacular.com/mozzarella-sticks-652513",
  },
  {
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 16,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 8,
    spoonacularScore: 91.0,
    healthScore: 56.0,
    pricePerServing: 316.16,
    extendedIngredients: [
      {
        id: 1019,
        aisle: "Cheese",
        image: "feta.png",
        consistency: "solid",
        name: "feta",
        nameClean: "feta cheese",
        original:
          "1/2 cup feta (preferably goat or sheep's milk) crumbled, plus extra for garnish",
        originalName:
          "feta (preferably goat or sheep's milk) crumbled, plus extra for garnish",
        amount: 0.5,
        unit: "cup",
        meta: ["crumbled", "for garnish", "(preferably goat or sheep's milk)"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "2 tablespoons olive oil",
        originalName: "olive oil",
        amount: 2.0,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 12147,
        aisle: "Produce;Baking",
        image: "pine-nuts.png",
        consistency: "solid",
        name: "pine nuts",
        nameClean: "pine nuts",
        original: "1/4 cup pine nuts",
        originalName: "pine nuts",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 59.147,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 10011282,
        aisle: "Produce",
        image: "red-onion.png",
        consistency: "solid",
        name: "red onion",
        nameClean: "red onion",
        original: "1 small large red onion, chopped into pieces",
        originalName: "red onion, chopped into pieces",
        amount: 1.0,
        unit: "small",
        meta: ["red", "chopped"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "small",
            unitLong: "small",
          },
          metric: {
            amount: 1.0,
            unitShort: "small",
            unitLong: "small",
          },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "solid",
        name: "salt",
        nameClean: "table salt",
        original: "1/4 teaspoon salt",
        originalName: "salt",
        amount: 0.25,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 10011457,
        aisle: "Produce",
        image: "spinach.jpg",
        consistency: "solid",
        name: "spinach",
        nameClean: "spinach",
        original: "5 cups fresh spinach, thoroughly washed",
        originalName: "fresh spinach, thoroughly washed",
        amount: 5.0,
        unit: "cups",
        meta: ["fresh", "washed"],
        measures: {
          us: {
            amount: 5.0,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 1.183,
            unitShort: "l",
            unitLong: "liters",
          },
        },
      },
      {
        id: 11529,
        aisle: "Produce",
        image: "tomato.png",
        consistency: "solid",
        name: "tomatoes",
        nameClean: "tomato",
        original:
          "1/2 pound ripe small tomatoes (preferably strawberry, cherry or",
        originalName: "ripe small tomatoes (preferably strawberry, cherry or",
        amount: 0.5,
        unit: "pound",
        meta: ["ripe"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "lb",
            unitLong: "pounds",
          },
          metric: {
            amount: 226.796,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "liquid",
        name: "water",
        nameClean: "water",
        original: "1 1/2 cups water",
        originalName: "water",
        amount: 1.5,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 1.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 354.882,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 99024,
        aisle: "Pasta and Rice",
        image: "couscous-cooked.jpg",
        consistency: "solid",
        name: "whole-wheat couscous",
        nameClean: "whole wheat couscous",
        original: "1 cup whole-wheat couscous",
        originalName: "whole-wheat couscous",
        amount: 1.0,
        unit: "cup",
        meta: ["whole-wheat"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 661365,
    title: "Spinach, Tomato & Onion Couscous",
    readyInMinutes: 45,
    servings: 3,
    sourceUrl:
      "http://www.foodista.com/recipe/SVZDH8S4/spinach-tomato-onion-couscous",
    image: "https://spoonacular.com/recipeImages/661365-556x370.jpg",
    imageType: "jpg",
    summary:
      'Spinach, Tomato & Onion Couscous might be just the main course you are searching for. Watching your figure? This vegetarian recipe has <b>555 calories</b>, <b>19g of protein</b>, and <b>24g of fat</b> per serving. This recipe serves 3 and costs $3.16 per serving. If you have salt, olive oil, onion, and a few other ingredients on hand, you can make it. To use up the pine nuts you could follow this main course with the <a href="https://spoonacular.com/recipes/pear-cake-with-pine-nuts-167404">Pear Cake with Pine Nuts</a> as a dessert. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. 8 people have tried and liked this recipe. All things considered, we decided this recipe <b>deserves a spoonacular score of 92%</b>. This score is spectacular. Try <a href="https://spoonacular.com/recipes/roasted-garlic-couscous-with-tomatoes-dill-onion-and-spinach-497176">Roasted Garlic Couscous with Tomatoes, Dill, Onion, and Spinach</a>, <a href="https://spoonacular.com/recipes/lamb-chops-with-spinach-tomato-couscous-494031">Lamb Chops with Spinach Tomato Couscous</a>, and <a href="https://spoonacular.com/recipes/feta-and-green-onion-couscous-cakes-over-tomato-olive-salad-133311">Fetan and Green Onion Couscous Cakes over Tomato-Olive Salad</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["lacto ovo vegetarian"],
    occasions: [],
    instructions:
      "<ol><li>Bring the water, along with half the salt, to a boil in a small pan.  Once boiling, add the couscous, stir and cover with a lid.  Remove the pot from the heat, and allow it to sit for the 5 to 7 minutes it takes to cook the vegetables.</li><li>Heat a large pan over medium-high heat and add the 2 tablespoons of olive oil.  Once the oil is hot, add the onions and saut until they begin to brown.  Add the tomatoes and remaining salt and saut until they begin to wilt, about 20 to 30 seconds.  Add the spinach and saut just until it wilts but remains bright green. Finally, stir the pine nuts into the vegetable mixture and remove the pan from the heat.  Season with salt and pepper to taste.</li><li>Pour the couscous into a large bowl, add the sauted vegetables along with the crumbled feta and toss everything together.  Top with the extra crumbled feta and enjoy while hot.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Bring the water, along with half the salt, to a boil in a small pan.  Once boiling, add the couscous, stir and cover with a lid.",
            ingredients: [
              {
                id: 20028,
                name: "couscous",
                localizedName: "couscous",
                image: "couscous-cooked.jpg",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 2,
            step: "Remove the pot from the heat, and allow it to sit for the 5 to 7 minutes it takes to cook the vegetables.",
            ingredients: [
              {
                id: 11583,
                name: "vegetable",
                localizedName: "vegetable",
                image: "mixed-vegetables.png",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
            length: {
              number: 5,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step: "Heat a large pan over medium-high heat and add the 2 tablespoons of olive oil.  Once the oil is hot, add the onions and saut until they begin to brown.",
            ingredients: [
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 4,
            step: "Add the tomatoes and remaining salt and saut until they begin to wilt, about 20 to 30 seconds.",
            ingredients: [
              {
                id: 11529,
                name: "tomato",
                localizedName: "tomato",
                image: "tomato.png",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Add the spinach and saut just until it wilts but remains bright green. Finally, stir the pine nuts into the vegetable mixture and remove the pan from the heat.  Season with salt and pepper to taste.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 12147,
                name: "pine nuts",
                localizedName: "pine nuts",
                image: "pine-nuts.png",
              },
              {
                id: 11583,
                name: "vegetable",
                localizedName: "vegetable",
                image: "mixed-vegetables.png",
              },
              {
                id: 10011457,
                name: "spinach",
                localizedName: "spinach",
                image: "spinach.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 6,
            step: "Pour the couscous into a large bowl, add the sauted vegetables along with the crumbled feta and toss everything together.  Top with the extra crumbled feta and enjoy while hot.",
            ingredients: [
              {
                id: 11583,
                name: "vegetable",
                localizedName: "vegetable",
                image: "mixed-vegetables.png",
              },
              {
                id: 20028,
                name: "couscous",
                localizedName: "couscous",
                image: "couscous-cooked.jpg",
              },
              {
                id: 1019,
                name: "feta cheese",
                localizedName: "feta cheese",
                image: "feta.png",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
        ],
      },
    ],
    sourceName: null,
    creditsText: null,
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/spinach-tomato-onion-couscous-661365",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 12,
    gaps: "no",
    lowFodmap: true,
    aggregateLikes: 58,
    spoonacularScore: 95.0,
    healthScore: 33.0,
    pricePerServing: 96.34,
    extendedIngredients: [
      {
        id: 93607,
        aisle: "Milk, Eggs, Other Dairy",
        image: "almond-milk.png",
        consistency: "liquid",
        name: "almond milk",
        nameClean: "almond milk",
        original:
          "1 cup almond milk or other non-dairy milk (see my almond milk recipe)",
        originalName:
          "almond milk or other non-dairy milk (see my almond milk recipe)",
        amount: 1.0,
        unit: "cup",
        meta: ["(see my almond milk recipe)"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 9040,
        aisle: "Produce",
        image: "bananas.jpg",
        consistency: "solid",
        name: "bananas",
        nameClean: "ripe banana",
        original: "2 bananas, smashed (I used frozen)",
        originalName: "bananas, smashed (I used frozen)",
        amount: 2.0,
        unit: "",
        meta: ["frozen", "smashed", "(I used )"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 16098,
        aisle: "Nut butters, Jams, and Honey",
        image: "peanut-butter.png",
        consistency: "solid",
        name: "peanut butter",
        nameClean: "peanut butter",
        original: "1/2 cup peanut butter",
        originalName: "peanut butter",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 9316,
        aisle: "Produce",
        image: "strawberries.png",
        consistency: "solid",
        name: "strawberries",
        nameClean: "strawberries",
        original:
          "½ cup strawberries (about 3 strawberries) or 1 Tbsp strawberry jam",
        originalName:
          "strawberries (about 3 strawberries) or 1 Tbsp strawberry jam",
        amount: 0.5,
        unit: "cup",
        meta: ["( 3 strawberries)"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 655235,
    title: "Peanut Butter and Jelly Smoothie",
    readyInMinutes: 45,
    servings: 2,
    sourceUrl:
      "http://www.foodista.com/recipe/K5KVRWVR/peanut-butter-and-jelly-smoothie",
    image: "https://spoonacular.com/recipeImages/655235-556x370.jpg",
    imageType: "jpg",
    summary:
      'Peanut Butter and Jelly Smoothie might be just the morn meal you are searching for. For <b>96 cents per serving</b>, this recipe <b>covers 20%</b> of your daily requirements of vitamins and minerals. This recipe makes 2 servings with <b>513 calories</b>, <b>18g of protein</b>, and <b>34g of fat</b> each. A few people made this recipe, and 58 would say it hit the spot. If you have almond milk, bananas, peanut butter, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. It is a good option if you\'re following a <b>gluten free, dairy free, and fodmap friendly</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 96%</b>. This score is awesome. Similar recipes include <a href="https://spoonacular.com/recipes/peanut-butter-and-jelly-smoothie-609137">Peanut Butter and Jelly Smoothie</a>, <a href="https://spoonacular.com/recipes/peanut-butter-and-jelly-smoothie-631463">Peanut Butter and Jelly Smoothie</a>, and <a href="https://spoonacular.com/recipes/peanut-butter-and-jelly-smoothie-472194">Peanut Butter and Jelly Smoothie</a>.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "fodmap friendly"],
    occasions: [],
    instructions:
      "<ol><li>Place ingredients in a high speed blender like Blendtec for super smooth texture, blend on high.</li><li>If using a regular blender put milk and strawberries in then blend.</li><li>Next, add banana pieces and peanut butter, process until smooth.</li><li>Garnish with crushed peanuts and serve.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Place ingredients in a high speed blender like Blendtec for super smooth texture, blend on high.If using a regular blender put milk and strawberries in then blend.Next, add banana pieces and peanut butter, process until smooth.",
            ingredients: [
              {
                id: 16098,
                name: "peanut butter",
                localizedName: "peanut butter",
                image: "peanut-butter.png",
              },
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
              {
                id: 9040,
                name: "banana",
                localizedName: "banana",
                image: "bananas.jpg",
              },
              {
                id: 1077,
                name: "milk",
                localizedName: "milk",
                image: "milk.png",
              },
            ],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
            ],
          },
          {
            number: 2,
            step: "Garnish with crushed peanuts and serve.",
            ingredients: [
              {
                id: 16091,
                name: "peanuts",
                localizedName: "peanuts",
                image: "peanuts.png",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    sourceName: null,
    creditsText: null,
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/peanut-butter-and-jelly-smoothie-655235",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 10,
    gaps: "no",
    lowFodmap: false,
    preparationMinutes: 10,
    cookingMinutes: 480,
    aggregateLikes: 6,
    spoonacularScore: 62.0,
    healthScore: 15.0,
    pricePerServing: 163.29,
    extendedIngredients: [
      {
        id: 19056,
        aisle: "Savory Snacks",
        image: "tortilla-chips.jpg",
        consistency: "solid",
        name: "nacho chips",
        nameClean: "corn tortilla chips",
        original: "1 bag nacho chips",
        originalName: "nacho chips",
        amount: 1.0,
        unit: "bag",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "bag",
            unitLong: "bag",
          },
          metric: {
            amount: 1.0,
            unitShort: "bag",
            unitLong: "bag",
          },
        },
      },
      {
        id: 27027,
        aisle: "Canned and Jarred;Ethnic Foods",
        image: "pico-de-gallo.png",
        consistency: "solid",
        name: "pico de gallo",
        nameClean: "pico de gallo",
        original: "1 cup pico de gallo",
        originalName: "pico de gallo",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1072034,
        aisle: "Spices and Seasonings",
        image: "seasoning.jpg",
        consistency: "solid",
        name: "pork rub",
        nameClean: "pork seasoning",
        original: "4 tbsp pork rub",
        originalName: "pork rub",
        amount: 4.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: {
            amount: 4.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 4.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 10072,
        aisle: "Meat",
        image: "pork-shoulder.png",
        consistency: "solid",
        name: "pork shoulder",
        nameClean: "pork shoulder",
        original: "1 2lb pork shoulder",
        originalName: "pork shoulder",
        amount: 2.0,
        unit: "lb",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "lb",
            unitLong: "pounds",
          },
          metric: {
            amount: 907.185,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 1011026,
        aisle: "Cheese",
        image: "cheddar-cheese.png",
        consistency: "solid",
        name: "shredded cheese",
        nameClean: "shredded cheese",
        original: "1/2 cup shredded cheese",
        originalName: "shredded cheese",
        amount: 0.5,
        unit: "cup",
        meta: ["shredded"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1056,
        aisle: "Milk, Eggs, Other Dairy",
        image: "sour-cream.jpg",
        consistency: "solid",
        name: "sour cream",
        nameClean: "sour cream",
        original: "2 tbsp sour cream",
        originalName: "sour cream",
        amount: 2.0,
        unit: "tbsp",
        meta: ["sour"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 6615,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "liquid",
        name: "vegetable broth",
        nameClean: "vegetable stock",
        original: "2 cups vegetable broth",
        originalName: "vegetable broth",
        amount: 2.0,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 473.176,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 1039293,
    title: "Pulled Pork Nachos",
    readyInMinutes: 490,
    servings: 8,
    sourceUrl: "https://www.pinkwhen.com/pulled-pork-nachos/",
    image: "https://spoonacular.com/recipeImages/1039293-556x370.jpg",
    imageType: "jpg",
    summary:
      'You can never have too many hor d\'oeuvre recipes, so give Pulled Pork Nachos a try. This recipe makes 8 servings with <b>358 calories</b>, <b>19g of protein</b>, and <b>17g of fat</b> each. For <b>$1.63 per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. Not a lot of people made this recipe, and 6 would say it hit the spot. This recipe is typical of Mexican cuisine. This recipe from Pink When requires pork shoulder, vegetable broth, nacho chips, and cheese. It is a good option if you\'re following a <b>gluten free</b> diet. From preparation to the plate, this recipe takes approximately <b>8 hours and 10 minutes</b>. Overall, this recipe earns a <b>rather bad spoonacular score of 14%</b>. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/pulled-pork-nachos-498935">Pulled Pork Nachos</a>, <a href="https://spoonacular.com/recipes/pulled-pork-nachos-687166">Pulled Pork Nachos</a>, and <a href="https://spoonacular.com/recipes/pulled-pork-nachos-754323">Pulled Pork Nachos</a>.',
    cuisines: ["American"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free"],
    occasions: [],
    instructions:
      "InstructionsClean the pork and pat dry. Add the pork rub to the shoulder and season all over. Place the pork shoulder into the crock pot and set the temperature to low. Add in the vegetable broth and cook on low for 8-10 hours. Remove from slow cooker and shred the pork. Top the nachos with the shredded pork, pico de gallo, shredded cheese, and sour cream if desired.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Clean the pork and pat dry.",
            ingredients: [
              {
                id: 10010219,
                name: "pork",
                localizedName: "pork",
                image: "pork-tenderloin-raw.png",
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step: "Add the pork rub to the shoulder and season all over.",
            ingredients: [
              {
                id: 1072034,
                name: "pork seasoning",
                localizedName: "pork seasoning",
                image: "seasoning.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Place the pork shoulder into the crock pot and set the temperature to low.",
            ingredients: [
              {
                id: 10072,
                name: "pork shoulder",
                localizedName: "pork shoulder",
                image: "pork-shoulder.png",
              },
            ],
            equipment: [
              {
                id: 404718,
                name: "slow cooker",
                localizedName: "slow cooker",
                image: "slow-cooker.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Add in the vegetable broth and cook on low for 8-10 hours.",
            ingredients: [
              {
                id: 6615,
                name: "vegetable broth",
                localizedName: "vegetable broth",
                image: "chicken-broth.png",
              },
            ],
            equipment: [],
            length: {
              number: 600,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Remove from slow cooker and shred the pork. Top the nachos with the shredded pork, pico de gallo, shredded cheese, and sour cream if desired.",
            ingredients: [
              {
                id: 1011026,
                name: "shredded cheese",
                localizedName: "shredded cheese",
                image: "cheddar-cheese.png",
              },
              {
                id: 27027,
                name: "pico de gallo",
                localizedName: "pico de gallo",
                image: "pico-de-gallo.png",
              },
              {
                id: 98944,
                name: "pulled pork",
                localizedName: "pulled pork",
                image: "pulled-pork.png",
              },
              {
                id: 1056,
                name: "sour cream",
                localizedName: "sour cream",
                image: "sour-cream.jpg",
              },
              {
                id: 10010219,
                name: "pork",
                localizedName: "pork",
                image: "pork-tenderloin-raw.png",
              },
            ],
            equipment: [
              {
                id: 404718,
                name: "slow cooker",
                localizedName: "slow cooker",
                image: "slow-cooker.jpg",
              },
            ],
          },
        ],
      },
    ],
    sourceName: null,
    creditsText: null,
    originalId: null,
    spoonacularSourceUrl: "https://spoonacular.com/pulled-pork-nachos-1039293",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 3,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 31,
    spoonacularScore: 56.0,
    healthScore: 9.0,
    pricePerServing: 119.57,
    extendedIngredients: [
      {
        id: 10015172,
        aisle: "Seafood",
        image: "scallops.jpg",
        consistency: "solid",
        name: "scallops",
        nameClean: "scallops",
        original: "12 big fresh scallops (18 if they're small)",
        originalName: "12 big fresh scallops (18 if they're small)",
        amount: 12.0,
        unit: "small",
        meta: ["fresh", "(18 if they're small)"],
        measures: {
          us: {
            amount: 12.0,
            unitShort: "small",
            unitLong: "smalls",
          },
          metric: {
            amount: 12.0,
            unitShort: "small",
            unitLong: "smalls",
          },
        },
      },
      {
        id: 10151,
        aisle: "Meat",
        image: "ham-whole.jpg",
        consistency: "solid",
        name: "ham",
        nameClean: "ham",
        original: "4 thin slices of Parma ham",
        originalName: "thin slices of Parma ham",
        amount: 4.0,
        unit: "slices",
        meta: ["thin"],
        measures: {
          us: {
            amount: 4.0,
            unitShort: "slice",
            unitLong: "slices",
          },
          metric: {
            amount: 4.0,
            unitShort: "slice",
            unitLong: "slices",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic clove",
        nameClean: "garlic",
        original: "1 garlic clove",
        originalName: "garlic clove",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 18079,
        aisle: "Pasta and Rice",
        image: "breadcrumbs.jpg",
        consistency: "solid",
        name: "breadcrumbs",
        nameClean: "breadcrumbs",
        original: "3 tablespoons of dried breadcrumbs",
        originalName: "dried breadcrumbs",
        amount: 3.0,
        unit: "tablespoons",
        meta: ["dried"],
        measures: {
          us: {
            amount: 3.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 3.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 11297,
        aisle: "Produce;Spices and Seasonings",
        image: "parsley.jpg",
        consistency: "solid",
        name: "parsley",
        nameClean: "parsley",
        original: "2 tablespoons of parsley",
        originalName: "parsley",
        amount: 2.0,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "2 tablespoons of olive oil",
        originalName: "olive oil",
        amount: 2.0,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 10211821,
        aisle: "Produce",
        image: "bell-pepper-orange.png",
        consistency: "solid",
        name: "bell pepper",
        nameClean: "bell pepper",
        original: "Pepper",
        originalName: "Pepper",
        amount: 1.0,
        unit: "serving",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
    ],
    id: 633786,
    title: "Baked Scallops With Parma Ham",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      "https://www.foodista.com/recipe/HCYYJYBM/baked-scallops-with-parma-ham",
    image: "https://spoonacular.com/recipeImages/633786-556x370.jpg",
    imageType: "jpg",
    summary:
      'If you want to add more <b>dairy free</b> recipes to your collection, Baked Scallops With Parma Ham might be a recipe you should try. For <b>$1.2 per serving</b>, this recipe <b>covers 9%</b> of your daily requirements of vitamins and minerals. This recipe makes 6 servings with <b>153 calories</b>, <b>12g of protein</b>, and <b>8g of fat</b> each. A couple people made this recipe, and 31 would say it hit the spot. It works well as a main course. It is brought to you by Foodista. Head to the store and pick up big scallops, breadcrumbs, garlic clove, and a few other things to make it today. From preparation to the plate, this recipe takes approximately <b>approximately 45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 55%</b>. This score is solid. Similar recipes include <a href="https://spoonacular.com/recipes/chicken-with-crispy-parma-ham-219606">Chicken with crispy Parma ham</a>, <a href="https://spoonacular.com/recipes/cod-with-parma-ham-asparagus-1632">Cod With Parma Ham & Asparagus</a>, and <a href="https://spoonacular.com/recipes/parma-ham-peach-plates-219116">Parma ham & peach plates</a>.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["dairy free"],
    occasions: [],
    instructions:
      "Preheat oven to 410 F (210 C / T 7).\nMix breadcrumbs, Parma ham, garlic, parsley and 1 teaspoon of olive oil in a food processor.\nFold a piece of kitchen paper, pour 1 teaspoon of olive oil on it and use it to grease an oven rack.\nPlace scallops on the greased rack and top them with Parma ham mix.\nPour a dash of olive oil on top and bake in oven for 8 minutes.\nServe as a starter with a few leaves of lamb's lettuce or rocket if you like.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 410 F (210 C / T 7).",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
                temperature: {
                  number: 410.0,
                  unit: "Fahrenheit",
                },
              },
            ],
          },
          {
            number: 2,
            step: "Mix breadcrumbs, Parma ham, garlic, parsley and 1 teaspoon of olive oil in a food processor.",
            ingredients: [
              {
                id: 18079,
                name: "breadcrumbs",
                localizedName: "breadcrumbs",
                image: "breadcrumbs.jpg",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 11297,
                name: "parsley",
                localizedName: "parsley",
                image: "parsley.jpg",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 10151,
                name: "ham",
                localizedName: "ham",
                image: "ham-whole.jpg",
              },
            ],
            equipment: [
              {
                id: 404771,
                name: "food processor",
                localizedName: "food processor",
                image: "food-processor.png",
              },
            ],
          },
          {
            number: 3,
            step: "Fold a piece of kitchen paper, pour 1 teaspoon of olive oil on it and use it to grease an oven rack.",
            ingredients: [
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Place scallops on the greased rack and top them with Parma ham mix.",
            ingredients: [
              {
                id: 10015172,
                name: "scallops",
                localizedName: "scallops",
                image: "scallops.jpg",
              },
              {
                id: 10151,
                name: "ham",
                localizedName: "ham",
                image: "ham-whole.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Pour a dash of olive oil on top and bake in oven for 8 minutes.",
            ingredients: [
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 8,
              unit: "minutes",
            },
          },
          {
            number: 6,
            step: "Serve as a starter with a few leaves of lamb's lettuce or rocket if you like.",
            ingredients: [
              {
                id: 11190,
                name: "mache",
                localizedName: "mache",
                image: "lambs-lettuce.jpg",
              },
              {
                id: 11959,
                name: "arugula",
                localizedName: "arugula",
                image: "arugula-or-rocket-salad.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    sourceName: null,
    creditsText: null,
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/baked-scallops-with-parma-ham-633786",
  },
];

export default randomRecipes;
