export const intolerances = [
  "Diary",
  "Gluten",
  "Grain",
  "Egg",
  "Peanut",
  "Seafood",
  "Sesame",
  "Shellfish",
  "Soy",
  "Sulfite",
  "Tree Nut",
  "Wheat",
];

export const cuisine = [
  "African",
  "American",
  "British",
  "Cajun",
  "Caribbean",
  "Chinese",
  "Eastern European",
  "European",
  "French",
  "German",
  "Greek",
  "Indian",
  "Irish",
  "Italian",
  "Japanese",
  "Jewish",
  "Korean",
  "Latin American",
  "Mediterranean",
  "Mexican",
  "Nordic",
  "Southern",
  "Spanish",
  "Thai",
  "Vietnamese",
  "Middle Eastern",
];

export const mealType = [
  "main course",
  "side dish",
  "appetizer",
  "dessert",
  "salad",
  "bread",
  "breakfast",
  "soup",
  "beverage",
  "sauce",
  "marinade",
  "fingerfood",
  "snack",
  "drink",
];

//export const API_KEY = "563ec2ac4d8a474f87c6f1a2c3cc8f83";
export const API_KEY = "fbbde4668a8849148fadd3ba8dd69449";
